version: 2.1
executors:
  node-browsers:
    resource_class: medium
    docker:
      - image: circleci/node:8-browsers
jobs:
  build:
    executor: node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build
